package dashboard

import (
	"encoding/json"
	"os"
	"path/filepath"

	"flashflow/internal/tuning"
)

const tuningResultsDir = "experiments/008-tuning-validation/results"

// EvaluationPoint is one search-ledger point for the tuning view's
// best-so-far chart.
type EvaluationPoint struct {
	Index   int     `json:"index"`
	Utility float64 `json:"utility"`
	Valid   bool    `json:"valid"`
}

// HoldoutSummary is the subset of 008-C's holdout-validation output
// the tuning view needs to make overfitting visually obvious (master
// context rule 32) -- Development and Holdout utility shown side by
// side, never blended into one number.
type HoldoutSummary struct {
	BaselineDevUtility     float64 `json:"baseline_dev_utility"`
	WinnerDevUtility       float64 `json:"winner_dev_utility"`
	BaselineHoldoutUtility float64 `json:"baseline_holdout_utility"`
	WinnerHoldoutUtility   float64 `json:"winner_holdout_utility"`
	GeneralizationGap      float64 `json:"generalization_gap"`
	EvidenceTier           string  `json:"evidence_tier"`
}

// TuningSummary is everything the dashboard's tuning view shows: the
// full search ledger's best-so-far curve (reusing internal/tuning's
// own exported SearchResult type -- no dashboard-specific
// reimplementation of the search ledger's shape) and, if present, the
// holdout comparison.
type TuningSummary struct {
	Available        bool              `json:"available"`
	TunerVersion     string            `json:"tuner_version,omitempty"`
	Evaluations      []EvaluationPoint `json:"evaluations,omitempty"`
	BestSoFarUtility []float64         `json:"best_so_far_utility,omitempty"`
	Plateaued        bool              `json:"plateaued"`
	Holdout          *HoldoutSummary   `json:"holdout,omitempty"`
}

// LoadTuningSummary reads 008B's search ledger and 008C's holdout
// validation from disk, if present -- read-only, exactly the artifacts
// those experiments already wrote, never regenerated by the dashboard
// itself (rule 34).
func LoadTuningSummary() TuningSummary {
	ledgerPath := filepath.Join(tuningResultsDir, "008B-search-ledger.json")
	data, err := os.ReadFile(ledgerPath)
	if err != nil {
		return TuningSummary{Available: false}
	}
	var result tuning.SearchResult
	if err := json.Unmarshal(data, &result); err != nil {
		return TuningSummary{Available: false}
	}

	points := make([]EvaluationPoint, len(result.Evaluations))
	for i, e := range result.Evaluations {
		points[i] = EvaluationPoint{Index: e.Index, Utility: e.Utility, Valid: e.Valid}
	}

	summary := TuningSummary{
		Available: true, TunerVersion: result.TunerVersion,
		Evaluations: points, BestSoFarUtility: result.Convergence.BestSoFarUtility,
		Plateaued: result.Convergence.Plateaued,
	}

	if holdoutData, err := os.ReadFile(filepath.Join(tuningResultsDir, "008C-holdout-validation.json")); err == nil {
		var holdout struct {
			BaselineDevUtility     float64 `json:"baseline_dev_utility"`
			WinnerDevUtility       float64 `json:"winner_dev_utility"`
			BaselineHoldoutUtility float64 `json:"baseline_holdout_utility"`
			WinnerHoldoutUtility   float64 `json:"winner_holdout_utility"`
			GeneralizationGap      float64 `json:"generalization_gap"`
			EvidenceTier           string  `json:"evidence_tier"`
		}
		if err := json.Unmarshal(holdoutData, &holdout); err == nil {
			summary.Holdout = &HoldoutSummary{
				BaselineDevUtility: holdout.BaselineDevUtility, WinnerDevUtility: holdout.WinnerDevUtility,
				BaselineHoldoutUtility: holdout.BaselineHoldoutUtility, WinnerHoldoutUtility: holdout.WinnerHoldoutUtility,
				GeneralizationGap: holdout.GeneralizationGap, EvidenceTier: holdout.EvidenceTier,
			}
		}
	}
	return summary
}
